add_rules("mode.debug", "mode.release")

target("MainWindow")
    set_languages("c++11")
    add_rules("qt.shared")
    add_defines("MAINWINDOW_API")
    add_packages("vtk")
    add_includedirs("./")
    add_includedirs("../")
    add_files("*.cpp","*.h")
    add_files("../qrc/qianfan.qrc")
    add_files("../qrc/translations.qrc")
    add_files("../qrc/translations/MainWindow_zh_CN.ts")
    add_frameworks("QtCore","QtWidgets","QtGui","QtNetwork",
            "QtWebengineWidgets","QtWebview")

    add_deps("ModuleBase")
    add_deps("Settings")
    add_deps("MeshData")
    add_deps("DataProperty")
    add_deps("IO")
    add_deps("Geometry")
    add_deps("ModelData")
    add_deps("MainWidgets")
    add_deps("PostWidgets")
    add_deps("SolverControl")
    add_deps("ConfigOptions")
    add_deps("ProjectTree")
    add_deps("Material")
    add_deps("PythonModule")
    add_deps("GeometryWidgets")
    add_deps("GeometryCommand")
    add_deps("GmshModule")
    add_deps("PluginManager")
    add_deps("UserGuidence")
    add_deps("SARibbonBar")
    if is_plat("macosx", "linux") then
        add_rules("qt.plugin")
    elseif is_plat("windows") then
        add_deps("XGenerateReport")
        add_deps("SelfDefObject")
        if is_mode("debug") then
            add_rules("qt.console")
        end
    end
